 Fri, 06 Mar 2020 19:09:32  INFO test_login.py setUpClass [ line:39 ] ==================== 准备开始执行登录接口测试 ====================
 Fri, 06 Mar 2020 19:09:32  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13342884220', 'pwd': '123456'}
 Fri, 06 Mar 2020 19:09:32  INFO test_login.py test_login [ line:75 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Fri, 06 Mar 2020 19:09:32  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '150 71369970', 'pwd': '123456'}
 Fri, 06 Mar 2020 19:09:32  INFO test_login.py test_login [ line:75 ] 预期结果是：{"status":0,  "code":"20111", "data":None, "msg":"用户名或密码错误"}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Fri, 06 Mar 2020 19:09:32  INFO test_login.py tearDownClass [ line:45 ] ==================== 登录接口测试执行完毕====================
 Fri, 06 Mar 2020 19:09:32  INFO test_register.py setUpClass [ line:38 ] ==================== 准备开始执行注册接口测试 ====================
 Fri, 06 Mar 2020 19:09:33  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15209847651', 'pwd': '1234567', 'regname': 'user1'}
 Fri, 06 Mar 2020 19:09:33  ERROR test_register.py test_register [ line:69 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '成功'} != {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'}
- {'code': '10001', 'data': None, 'msg': '成功', 'status': 1}
+ {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?                                         ++
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register.py", line 66, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '成功'} != {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'}
- {'code': '10001', 'data': None, 'msg': '成功', 'status': 1}
+ {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?                                         ++

 Fri, 06 Mar 2020 19:09:33  INFO test_register.py tearDownClass [ line:44 ] ==================== 注册接口测试执行完毕====================
