 Wed, 11 Mar 2020 12:09:51  INFO test_search.py setUpClass [ line:57 ] ==================== 准备开始执行查询接口测试 ====================
 Wed, 11 Mar 2020 12:09:51  INFO http_request.py request [ line:53 ] 正在发送请求，请求地址：http://144.34.200.237:8080/admin/login， 请求参数：{'password': '123456', 'username': 'ceshijiagoushi'}
 Wed, 11 Mar 2020 12:09:51  INFO http_request.py request [ line:59 ] 正在发送请求，请求地址：http://144.34.200.237:8080/order/list， 请求参数：None
 Wed, 11 Mar 2020 12:09:53  ERROR test_search.py test_search [ line:94 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'} != {'code': 200, 'message': '操作成功', 'data': {'[5574 chars]e}]}}
Diff is 10555 characters long. Set self.maxDiff to None to see it.
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_search.py", line 90, in test_search
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'} != {'code': 200, 'message': '操作成功', 'data': {'[5574 chars]e}]}}
Diff is 10555 characters long. Set self.maxDiff to None to see it.
 Wed, 11 Mar 2020 12:09:53  INFO http_request.py request [ line:53 ] 正在发送请求，请求地址：http://144.34.200.237:8080/admin/login， 请求参数：{'password': '123456', 'username': 'ceshijiagoushi'}
 Wed, 11 Mar 2020 12:09:54  INFO test_search.py tearDownClass [ line:63 ] ==================== 查询接口测试执行完毕====================
