 Fri, 06 Mar 2020 23:00:49  INFO test_register.py setUpClass [ line:42 ] ==================== 准备开始执行注册接口测试 ====================
 Fri, 06 Mar 2020 23:00:49  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15209847324', 'pwd': '1234567', 'regname': 'user1'}
 Fri, 06 Mar 2020 23:00:49  ERROR test_register.py test_register [ line:76 ]  :: {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1} != {'code': '20110', 'data': None, 'msg': '手机号码已被注册', 'status': 0}
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ---                           --             ^

+ {'code': '20110', 'data': None, 'msg': '手机号码已被注册', 'status': 0}
?           +++                           ++++++               ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register.py", line 73, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1} != {'code': '20110', 'data': None, 'msg': '手机号码已被注册', 'status': 0}
 Fri, 06 Mar 2020 23:00:50  INFO test_register.py tearDownClass [ line:48 ] ==================== 注册接口测试执行完毕====================
